### ISSUE TITLE
GenericJson.clone() method blows up when trying to clone Google reads

### ISSUE THREAD

**Issue by davidadamsphd** [google/google-http-java-client#293]
From the Hellbender project (broadinstitute/hellbender#650):

When we copy a Google read (ie., a com.google.api.services.genomics.model.Read), we currently call into the GenericJson.clone() method, which uses reflection to deep copy the fields. However, this method seems to incorrectly try to instantiate a java.util.Arrays$ArrayList instead of a java.util.ArrayList, causing it to blow up during BQSR runs (as reported by @jean-philippe-martin):

    [Jul-13 1:36 PM] JP Martin: 
    2015-07-13T17:36:00.151Z: Error:  (5361981f0726257c): java.lang.IllegalArgumentException: unable to create new instance of class java.util.Arrays$ArrayList possibly because it is not public
    at com.google.api.client.util.Types.handleExceptionForNewInstance(Types.java:165)
    at com.google.api.client.util.Types.newInstance(Types.java:120)
    at com.google.api.client.util.Data.clone(Data.java:220)
    at com.google.api.client.util.Data.deepCopy(Data.java:307)
    at com.google.api.client.util.Data.clone(Data.java:222)
    at com.google.api.client.util.Data.deepCopy(Data.java:293)
    at com.google.api.client.util.GenericData.clone(GenericData.java:172)
    at com.google.api.client.json.GenericJson.clone(GenericJson.java:90)
    at com.google.api.services.genomics.model.Read.clone(Read.java:548)
    at org.broadinstitute.hellbender.utils.read.GoogleGenomicsReadToGATKReadAdapter.copy(GoogleGenomicsReadToGATKReadAdapter.java:619)

**Comment by ejona86** [comment]
`java.util.Arrays$ArrayList` is not the same as `java.util.ArrayList`. The former is created from 'Arrays.asList()' and is backed by a fixed-size array (`add()` and `remove()` aren't supported).

It looks like it would be possible to add support for `Arrays$ArrayList` to [Data](https://github.com/google/google-http-java-client/blob/dev/google-http-client/src/main/java/com/google/api/client/util/Data.java), but it also seems a bit non-trivial.

As a simple workaround, you should be able to swap to ArrayList. Is that easy enough to do?

**Comment by ejona86** [comment]
With info from a separate discussion, it seems swapping to ArrayList is non-trivial. Arrays$ArrayList is pretty common, so the library supporting it makes sense.

**Comment by jean-philippe-martin** [comment]
I can confirm that this solves the "unable to create new instance of class java.util.Arrays$ArrayList" that I was seeing. This particular program is now able to run to completion.

**Comment by jean-philippe-martin** [comment]
I don't seem to have the power to reopen this bug, but we're running into a new variant of this exact same problem, even using your fix that I mentioned earlier.

It would be nice to see a definitive fix to this problem.

The class that's giving us trouble this time is `com.google.common.collect.Lists$TransformingRandomAccessList`. Here's the stack trace:

````
Error:   (e0086ea6f7eea4e6): java.lang.IllegalArgumentException: unable to create new instance of class com.google.common.collect.Lists$TransformingRandomAccessList possibly because it is not public
	at com.google.api.client.util.Types.handleExceptionForNewInstance(Types.java:165)
	at com.google.api.client.util.Types.newInstance(Types.java:120)
	at com.google.api.client.util.Data.clone(Data.java:229)
	at com.google.api.client.util.Data.deepCopy(Data.java:302)
	at com.google.api.client.util.GenericData.clone(GenericData.java:172)
	at com.google.api.client.json.GenericJson.clone(GenericJson.java:90)
	at com.google.api.services.genomics.model.LinearAlignment.clone(LinearAlignment.java:128)
	at com.google.api.services.genomics.model.LinearAlignment.clone(LinearAlignment.java:34)
	at com.google.api.client.util.Data.clone(Data.java:212)
	at com.google.api.client.util.Data.deepCopy(Data.java:302)
	at com.google.api.client.util.GenericData.clone(GenericData.java:172)
	at com.google.api.client.json.GenericJson.clone(GenericJson.java:90)
	at com.google.api.services.genomics.model.Read.clone(Read.java:548)
	at org.broadinstitute.hellbender.utils.read.GoogleGenomicsReadToGATKReadAdapter.copy(GoogleGenomicsReadToGATKReadAdapter.java:637)
	at org.broadinstitute.hellbender.tools.dataflow.transforms.bqsr.ApplyBQSRTransform$ApplyBQSR.processElement(ApplyBQSRTransform.java:65)
````

(see https://github.com/broadinstitute/hellbender/issues/650 )

**Comment by jean-philippe-martin** [comment]
Since I can't reopen this one, I submitted a new issue (#297). If you prefer, feel free to delete that one and reopen this issue instead.
