### ISSUE TITLE
Subclasses extending GenericJson are not deserialized - Exception is thrown instead

### ISSUE THREAD

**Issue by mdepak** [google/google-http-java-client#357]
When some classes extend the GenericJson to map the unknown attributes and @Key annotation is used to explicitly map the attributes, the values in the JSON are not mapped to the attributes annotated with @Key. In this case exception is thrown.

**Project Pom:**

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>generic-json-test</groupId>
    <artifactId>generic-json-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client-gson</artifactId>
            <version>1.19.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.2.4</version>
        </dependency>
    </dependencies>
</project>

``` 
Employee.json file

{
  "name": "Bob",
  "empId": "345",
  "address" : {"state" : "xyz"},
  "unknownFiled" : "some value"
}

Employee.java 

```
import com.google.api.client.json.GenericJson;
import com.google.api.client.util.Key;

public final class Employee extends GenericJson{

    @Key
    private String name;

    @Key
    private String empId;

    @Key
    private Address address;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmpId() {
        return empId;
    }

    public void setEmpId(String empId) {
        this.empId = empId;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }
}

``` 

Address.java
```

import com.google.api.client.json.GenericJson;
import com.google.api.client.util.Key;

public class Address extends GenericJson{

    @Key
    private String state;

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }
}

```

EmployeeJSONDeserlizer:

```
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class EmployeeJSONDeserlizer {
    public static void main(String[] args) throws IOException {

        Gson gson = new GsonBuilder().setPrettyPrinting().create();

        String fileData = new String(Files.readAllBytes(Paths.get("Employee.json")));

        Employee employee = gson.fromJson(fileData, Employee.class);

        System.out.println(employee.getName());
        System.out.println(employee.getEmpId());
        System.out.println(employee.getAddress().getState());
    }
}

``` 
 
Exception Stack Trace:
 
```
Exception in thread "main" java.lang.IllegalArgumentException: Can not set com.gson.test.Address field com.gson.test.Employee.address to com.google.gson.internal.LinkedTreeMap
 at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
 at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
 at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
 at java.lang.reflect.Field.set(Field.java:764)
 at com.google.api.client.util.FieldInfo.setFieldValue(FieldInfo.java:245)
 at com.google.api.client.util.FieldInfo.setValue(FieldInfo.java:206)
 at com.google.api.client.util.GenericData.put(GenericData.java:103)
 at com.google.api.client.util.GenericData.put(GenericData.java:47)
 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188)
 at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
 at com.google.gson.Gson.fromJson(Gson.java:803)
 at com.google.gson.Gson.fromJson(Gson.java:768)
 at com.google.gson.Gson.fromJson(Gson.java:717)
 at com.google.gson.Gson.fromJson(Gson.java:689)
 at com.gson.test.EmployeeJSONDeserlizer.main(EmployeeJSONDeserlizer.java:20)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

```

**Comment by Horneth** [comment]
Hi ! Any news on this ? I'm running into the same issue

**Comment by mattwhisenhunt** [comment]
So I will assume you want to set `employee` in EmployeeJSONDeserlizer from a web request and not actually from a file:
```Java
    EmployeeApi service = new EmployeeApi("http://localhost:6464/static/Employee.json");
    EmployeeApi.Employee employee = service.getById(345);
```
This is the library of an http client after all :smile:. Sticking with the employee example from the original issue report I extended GenericUrl for a little magic, any key/value pair that is set with `put` gets added to the query string of the request.

EmployeeApi.java:
```Java
import com.google.api.client.http.GenericUrl;
import com.google.api.client.http.HttpRequest;
import com.google.api.client.http.HttpRequestFactory;
import com.google.api.client.http.HttpRequestInitializer;
import com.google.api.client.http.HttpResponse;
import com.google.api.client.http.HttpTransport;
import com.google.api.client.http.javanet.NetHttpTransport;
import com.google.api.client.json.GenericJson;
import com.google.api.client.json.JsonObjectParser;
import com.google.api.client.json.gson.GsonFactory;
import java.io.IOException;

public class EmployeeApi extends GenericUrl {

  static final HttpTransport HTTP_TRANSPORT = new NetHttpTransport();
  static final GsonFactory GSON_FACTORY = new GsonFactory();

  private HttpRequestFactory httpclient;

  EmployeeApi(String encodedUrl) {
    super(encodedUrl);

    httpclient = HTTP_TRANSPORT.createRequestFactory(new HttpRequestInitializer() {
      @Override
      public void initialize(HttpRequest request) {
        request.setParser(new JsonObjectParser(GSON_FACTORY));
      }
    });
  }

  Employee getById(int id){
    Employee val = null;
    try {
      this.put("id",id);
      HttpRequest req = httpclient.buildGetRequest(this);

      try {
        HttpResponse r = req.execute();

        try {
          val =  r.parseAs(Employee.class);

        } catch (IOException e) {
          System.err.println("Couldn't parse a response: "+ e);
        }
      } catch (IOException e) {
        System.err.println("Send Error: " + e);
      }

    } catch (IOException e) {
      System.err.println(e);
    }

    return val;
  }
}
```

If you want to access Gson classes directly you can remove the `@Key` annotations.

If neither of those are the answer you are looking for, let me know and I will dig deeper.

**Comment by JustinBeckwith** [comment]
Greetings! We haven't heard anything for a while on this issue. If you're still running into problems... please do let us know!

**Comment by F-Scippacercola** [comment]
Hi all, I believe that GenericJson works out-of-the-box with ObjectMapper but not with Gson. 
Try with it.
