### ISSUE TITLE
This library should compile with JDK9

### ISSUE THREAD

**Issue by jadekler** [google/google-http-java-client#445]
But, it does not. When I use JDK8, `mvn install` works. When I use JDK9, `mvn install` fails. Here is the failure from `mvn install` with JDK9:

```
[ERROR] --------------------
[ERROR]  Standard error from the DataNucleus tool + org.datanucleus.enhancer.DataNucleusEnhancer :
[ERROR] --------------------
[ERROR] Aug 07, 2018 1:41:49 PM org.datanucleus.enhancer.DataNucleusEnhancer <init>
INFO: DataNucleus Enhancer : Using ClassEnhancer "ASM" for API "JDO"
Aug 07, 2018 1:41:49 PM org.datanucleus.enhancer.DataNucleusEnhancer main
INFO: DataNucleus Enhancer (version 2.1.3) : Enhancement of classes
Aug 07, 2018 1:41:49 PM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.extensions.jdo.JdoDataStoreFactory$PrivateUtils$ComposedIdKey" has no MetaData or annotations.
Aug 07, 2018 1:41:49 PM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.extensions.jdo.JdoDataStoreFactory$JdoDataStore" has no MetaData or annotations.
Aug 07, 2018 1:41:49 PM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.extensions.jdo.JdoDataStoreFactory$PrivateUtils" has no MetaData or annotations.
Aug 07, 2018 1:41:49 PM org.datanucleus.jdo.metadata.JDOAnnotationReader processClassAnnotations
INFO: Class "com.google.api.client.extensions.jdo.JdoDataStoreFactory$JdoValue" has been specified with JDO annotations so using those.
Aug 07, 2018 1:41:49 PM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.extensions.jdo.JdoDataStoreFactory" has no MetaData or annotations.
Aug 07, 2018 1:41:49 PM org.datanucleus.enhancer.DataNucleusEnhancer main
SEVERE: DataNucleus Enhancer completed with an error. Please review the enhancer log for full details. Some classes may have been enhanced but some caused errors
Exception during population of metadata for com.google.api.client.extensions.jdo.JdoDataStoreFactory$JdoValue
org.datanucleus.exceptions.NucleusUserException: Exception during population of metadata for com.google.api.client.extensions.jdo.JdoDataStoreFactory$JdoValue
	at org.datanucleus.metadata.MetaDataManager$1.run(MetaDataManager.java:2402)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.datanucleus.metadata.MetaDataManager.populateAbstractClassMetaData(MetaDataManager.java:2387)
	at org.datanucleus.metadata.MetaDataManager.populateFileMetaData(MetaDataManager.java:2224)
	at org.datanucleus.metadata.MetaDataManager.initialiseFileMetaDataForUse(MetaDataManager.java:924)
	at org.datanucleus.metadata.MetaDataManager.loadClasses(MetaDataManager.java:489)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:791)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:582)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1316)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Arrays.binarySearch(Arrays.java:2381)
	at org.datanucleus.store.types.TypeManager.isDefaultEmbeddedType(TypeManager.java:228)
	at org.datanucleus.metadata.AbstractMemberMetaData.populate(AbstractMemberMetaData.java:484)
	at org.datanucleus.metadata.ClassMetaData.populateMemberMetaData(ClassMetaData.java:543)
	at org.datanucleus.metadata.ClassMetaData.populate(ClassMetaData.java:210)
	at org.datanucleus.metadata.MetaDataManager$1.run(MetaDataManager.java:2393)
	... 8 more
Nested Throwables StackTrace:
java.lang.NullPointerException
	at java.base/java.util.Arrays.binarySearch(Arrays.java:2381)
	at org.datanucleus.store.types.TypeManager.isDefaultEmbeddedType(TypeManager.java:228)
	at org.datanucleus.metadata.AbstractMemberMetaData.populate(AbstractMemberMetaData.java:484)
	at org.datanucleus.metadata.ClassMetaData.populateMemberMetaData(ClassMetaData.java:543)
	at org.datanucleus.metadata.ClassMetaData.populate(ClassMetaData.java:210)
	at org.datanucleus.metadata.MetaDataManager$1.run(MetaDataManager.java:2393)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.datanucleus.metadata.MetaDataManager.populateAbstractClassMetaData(MetaDataManager.java:2387)
	at org.datanucleus.metadata.MetaDataManager.populateFileMetaData(MetaDataManager.java:2224)
	at org.datanucleus.metadata.MetaDataManager.initialiseFileMetaDataForUse(MetaDataManager.java:924)
	at org.datanucleus.metadata.MetaDataManager.loadClasses(MetaDataManager.java:489)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:791)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:582)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1316)
```

**Comment by chingor13** [comment]
We likely cannot fix this compilation issue as it happens in guava as well (where this code was extracted from). It seems that the Java 9 compiler is too strict and it won't be updated in the Java 9 JDK.
