### ISSUE TITLE
Data.clone cannot handle ImmutableList

### ISSUE THREAD

**Issue by wonderfly** [google/google-http-java-client#71]
_From [yan...@google.com](https://code.google.com/u/111815493751521097215/) on February 29, 2012 11:27:49_

Version of google-http-java-client (e.g. 1.5.0-beta)? http://docs.guava-libraries.googlecode.com/git-history/v11.0.2/javadoc/com/google/common/collect/ImmutableList.html http://javadoc.google-http-java-client.googlecode.com/hg/1.6.0-beta/com/google/api/client/util/Data.html#clone(T) Java environment (e.g. Java 6, Android 2.3, App Engine)? All Describe the problem. This code:
Data.clone(ImmutableList.of("a", "b", "c"))

throws this exception:
java.lang.IllegalArgumentException: unable to create new instance of class com.google.common.collect.RegularImmutableList possibly because it is not public
    at com.google.api.client.util.Types.handleExceptionForNewInstance(Types.java:167)
    at com.google.api.client.util.Types.newInstance(Types.java:122)
    at com.google.api.client.util.Data.clone(Data.java:222) How would you expect it to be fixed? It should not throw an exception and return a new instance of ImmutableList that is a deep clone of the original, like it doesfor other List implementations like ArrayList.

_Original issue: http://code.google.com/p/google-http-java-client/issues/detail?id=71_

**Comment by vertexclique** [comment]
Hi! What happened to this issue?
